### ISSUE TITLE
Timestamp issues

### ISSUE THREAD

**Issue by dantodor** [roapi/roapi#37]
First of all, thanks for including the Date32 in the latest commit.

I have checked out the code, build it with `--release` (btw, you might want to update the readme, the cargo command doesn't works because now you have two targets, roapi and columnq). Ubuntu 18, Rust updated to latest stable.

I have a few parquet files, in which datetime is stored in various formats, form Scala - Timestamp, DateTime, Long.
If I load the ones with Timestamp and DateTime, the result is the same for `select * from tbl limit 1` :
```
[2021-04-12T06:43:04Z INFO  actix_web::middleware::logger] 127.0.0.1:33584 "POST /api/sql HTTP/1.1" 200 29 "-" "curl/7.58.0" 0.012752
thread 'actix-rt|system:0|arbiter:1' panicked at 'Unsupported datatype: Timestamp(
    Nanosecond,
    None,
)', /root/.cargo/git/checkouts/arrow-7d34e669e95701bb/cfec7bc/rust/arrow/src/json/writer.rs:326:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/panicking.rs:435:5
   2: arrow::json::writer::set_column_for_json_rows
   3: arrow::json::writer::record_batches_to_json_rows
   4: roapi_http::encoding::json::record_batches_to_bytes
   5: roapi_http::api::encode_record_batches
```

Now, I was thinking that I can live with Long values, and use the `to_timestamp` function. But I get the same error. Here's an example from the output:

```
curl -X POST -d "select to_timestamp('2020-09-08T12:00:00+00:00') from tbl limit 1" localhost:8091/api/sql
[2021-04-12T06:58:35Z INFO  actix_web::middleware::logger] 127.0.0.1:33678 "POST /api/sql HTTP/1.1" 400 170 "-" "curl/7.58.0" 0.003689
thread 'actix-rt|system:0|arbiter:4' panicked at 'Unsupported datatype: Timestamp(
    Nanosecond,
    None,
)', /root/.cargo/git/checkouts/arrow-7d34e669e95701bb/cfec7bc/rust/arrow/src/json/writer.rs:326:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/panicking.rs:435:5
   2: arrow::json::writer::set_column_for_json_rows
   3: arrow::json::writer::record_batches_to_json_rows
   4: roapi_http::encoding::json::record_batches_to_bytes
   5: roapi_http::api::encode_record_batches
```

And the value above comes from the Datafusion tests, which are presumably working : [https://github.com/apache/arrow/blob/5b08205f7e864ed29f53ed3d836845fed62d5d4a/rust/datafusion/tests/sql.rs#L1768](url)

I am a little puzzled right now. Do you see a way in which I can use timestamps in conjuction with roapi ?
Is my understanding correct, that at this moment I can use Date, but not DateTime, Timestamp ?

**Comment by dantodor** [comment]
Please forget it, I'm an idiot ... I was running the previous version
