### ISSUE TITLE
Inlude new files in registry

### ISSUE THREAD

**Issue by jbremmer** [roapi/roapi#55]
As ROAPI User
I would like to point to folder containing files (JSON/Parque/etc)
and be able to include new files (as in added after ROAPI start) in query results.

**Comment by houqp** [comment]
Streaming update is definitely something I wanted to add to roapi as well :)

@jbremmer how are you deploying roapi with corresponding files today?

**Comment by dispanser** [comment]
Option 3 seems rather hard to implement. I expect it needs some form of support from the underlying storage system. I believe both S3 and Azure have something like that, but we probably need a separate implementation for each of those, and there is non-trivial machinery involved, at least in [azure](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-event-overview)

Wrt the other two options:

It also depends on the both the storage format and the table format. For cloud storage, repeatedly updating file listings (parquet, ...) may become expensive, whereas keeping up to date with a delta table is relatively cheap. 

As this piece of functionality is required for my use case, I will try to look into this, maybe next weekend.

**Comment by jbremmer** [comment]
Having operational endpoint to refresh specific folder, or simply point to new file would be nice workaround too.

@houqp I have bunch of parquet files on local file system (about to move to S3).

**Comment by houqp** [comment]
> Option 3 seems rather hard to implement. I expect it needs some form of support from the underlying storage system. I believe both S3 and Azure have something like that, but we probably need a separate implementation for each of those, and there is non-trivial machinery involved, at least in azure

Yes, this requires support from the underlying storage system or table format. s3 event notification for aws, inotify for local fs, etc. For table formats like delta tables, we can also fall back to simple polling of latest version.

**Comment by dispanser** [comment]
Just for reference, delta has a config (at spark session level), `spark.databricks.delta.stalenessLimit` which represents a time unit with maximum allowed staleness. Since this is per session, it would be conceptually close to the 1. (query parameter `maxAge`) above.

**Comment by houqp** [comment]
@brycefisher the partition support you mentioned got merged into datafusion recently (see https://github.com/apache/arrow-datafusion/pull/1141), although right now it only works for local filesystem. But we should be able to get this support for free once other object stores are added to datafusion.

> Regarding Option 3, perhaps ROAPI could expose a REST API endpoint to allow an external system to trigger a refresh. This would allow you to automatically refresh any backing storage going forward without having to ship inotify, sns, pub/sub, eventhub integrations from day one.

I think push based update is also a good feature to add, thanks for the suggestion :)

So to summarize, here are the features we could add to support data refresh in different scenarios:

1. an additional query parameter, say, maxAge that triggers roapi to rescan / reload the files
2. a configuration option that defines some sort of update interval
3. subscribe to table source update event if supported by the table/source type
4. expose to endpoint/webhook to allow external system to trigger refresh

**Comment by cymqqqq** [comment]
an additional query parameter, say, maxAge that triggers roapi to rescan / reload the files
a configuration option that defines some sort of update interval
subscribe to table source update event if supported by the table/source type
expose to endpoint/webhook to allow external system to trigger refresh
I here again
Did any of the above four options has implemented? :)

**Comment by houqp** [comment]
4. is under review at https://github.com/roapi/roapi/pull/154. The other options haven't been implemented yet, but PRs welcome.

**Comment by cymqqqq** [comment]
thx bro :)

**Comment by houqp** [comment]
Thanks to @zemelLeong , we now have option 4 fully implemented with a solid infrastructure to support runtime table updates. option 1, 2 and 3 should be pretty trivia to implement now if we reuse the same infrastructure.

**Comment by whatrocks** [comment]
Option 1 is now implemented. Try adding this to your roapi command: `-r 3600`

**Comment by mrchypark** [comment]
I tried -r 3600 with cli, I got error. I use v0.11.3

```
RUST_BACKTRACE=full ./roapi -r 3600 -c roapi.yaml -d
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.2/src/parser/error.rs:32:9:
Mismatch between definition and access of `reload-interval`. Could not downcast to TypeId { t: 211145317803461539246944466681743340709 }, need to downcast to TypeId { t: 247962479967627837999251560468041260107 }

stack backtrace:
   0:          0x21f0404 - std::backtrace_rs::backtrace::libunwind::trace::hcc3ffcf602aeb3f9
                               at /rustc/878c8a2a62d49ca5c454547ad67290a1df746cb5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:          0x21f0404 - std::backtrace_rs::backtrace::trace_unsynchronized::h4d11f1856594b3de
                               at /rustc/878c8a2a62d49ca5c454547ad67290a1df746cb5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:          0x21f0404 - std::sys_common::backtrace::_print_fmt::h56e05411a88a9113
                               at /rustc/878c8a2a62d49ca5c454547ad67290a1df746cb5/library/std/src/sys_common/backtrace.rs:68:5
   3:          0x21f0404 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h477649c552655cf7
                               at /rustc/878c8a2a62d49ca5c454547ad67290a1df746cb5/library/std/src/sys_common/backtrace.rs:44:22
   4:           0xf2b748 - core::fmt::rt::Argument::fmt::h7c30fefcde82879a
                               at /rustc/878c8a2a62d49ca5c454547ad67290a1df746cb5/library/core/src/fmt/rt.rs:142:9
   5:           0xf2b748 - core::fmt::write::h285c07517a6cc718
                               at /rustc/878c8a2a62d49ca5c454547ad67290a1df746cb5/library/core/src/fmt/mod.rs:1120:17
   6:          0x21c4838 - std::io::Write::write_fmt::h51ef3a306ca7bdee
                               at /rustc/878c8a2a62d49ca5c454547ad67290a1df746cb5/library/std/src/io/mod.rs:1846:15
   7:          0x21f1744 - std::sys_common::backtrace::_print::h6e0667f7ddd71146
                               at /rustc/878c8a2a62d49ca5c454547ad67290a1df746cb5/library/std/src/sys_common/backtrace.rs:47:5
   8:          0x21f1744 - std::sys_common::backtrace::print::h28fd6df394d2cf3d
                               at /rustc/878c8a2a62d49ca5c454547ad67290a1df746cb5/library/std/src/sys_common/backtrace.rs:34:9
   9:          0x21f1008 - std::panicking::default_hook::{{closure}}::h4817439a46a688e4
                               at /rustc/878c8a2a62d49ca5c454547ad67290a1df746cb5/library/std/src/panicking.rs:272:22
  10:          0x21f1fa8 - std::panicking::default_hook::hdae94c34a045410c
                               at /rustc/878c8a2a62d49ca5c454547ad67290a1df746cb5/library/std/src/panicking.rs:292:9
  11:          0x21f1fa8 - std::panicking::rust_panic_with_hook::h92499ddc3613d759
                               at /rustc/878c8a2a62d49ca5c454547ad67290a1df746cb5/library/std/src/panicking.rs:779:13
  12:          0x21f1a80 - std::panicking::begin_panic_handler::{{closure}}::h39b7e0b1891a13bc
                               at /rustc/878c8a2a62d49ca5c454547ad67290a1df746cb5/library/std/src/panicking.rs:657:13
  13:          0x21f19f0 - std::sys_common::backtrace::__rust_end_short_backtrace::h197ffd1b729fcb5d
                               at /rustc/878c8a2a62d49ca5c454547ad67290a1df746cb5/library/std/src/sys_common/backtrace.rs:171:18
  14:          0x21f19e8 - rust_begin_unwind
                               at /rustc/878c8a2a62d49ca5c454547ad67290a1df746cb5/library/std/src/panicking.rs:645:5
  15:           0x43a0a0 - core::panicking::panic_fmt::h6a52dd3ef190e5c7
                               at /rustc/878c8a2a62d49ca5c454547ad67290a1df746cb5/library/core/src/panicking.rs:72:14
  16:          0x1e7c5bc - roapi::config::get_configuration::h77884271ac4503f5
  17:           0x7fb4a4 - roapi::main::{{closure}}::h65cb304f36bb1924
  18:           0x7f7a2c - roapi::main::hf8ece59c33f0fcdc
  19:           0x5de790 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1949da3a922dd346
  20:           0x5e0694 - std::rt::lang_start::{{closure}}::h10b75704edabce31
  21:           0x7fe4f4 - main```

**Comment by houqp** [comment]
What configuration are you trying to make?

**Comment by chrisfw** [comment]
Hi @houqp ,

I was envisioning a parquet file datasource that is refreshed preferably on demand, or alternatively on a refresh schedule.  That dataset could be exposed and pulled down using the fast transfer enabled by Arrow Flight.

Can you provide a sample command line/config that would configure ROAPI this way?

Thanks,
Chris

**Comment by chrisfw** [comment]
> Hi [@houqp](https://github.com/houqp) ,
> 
> I was envisioning a parquet file datasource that is refreshed preferably on demand, or alternatively on a refresh schedule. That dataset could be exposed and pulled down using the fast transfer enabled by Arrow Flight.
> 
> Can you provide a sample command line/config that would configure ROAPI this way?
> 
> Thanks, Chris

Hi @houqp , I just wanted to follow up on this to see if you can provide me with the command line or config file entries that will allow me to serve a dataset based on parquet file(s), refresh it every 15 minutes and serve the data over an arrow flight endpoint.  Can you assist me with this?

Thank you!

Regards,
Chris

**Comment by chrisfw** [comment]
Hi @houqp , I just wanted to follow up on the command line question above.  Would you be able to provide a sample command line for the config I described?

Thank you!

Regards,
Chris

**Comment by chrisfw** [comment]
@houqp , I have been experimenting with refreshes successfully using option 2, but I would also like to try out refreshing using option 4 and hit the api endpoint.  Can you please provide an example of how to invoke a refresh for a table using a ROAPI api call?

Thank you!
Chris
